name: Simple CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download code
      uses: actions/checkout@v3

    - name: Start services
      run: |
        docker compose up -d --build
        echo "Waiting for DB + APIâ€¦"
        sleep 20

    - name: Show container logs (debug)
      run: |
        echo "=== API LOGS ==="
        docker compose logs api
        echo "=== DB LOGS ==="
        docker compose logs db

    - name: Run tests
      run: |
        docker compose ps
        docker compose exec -T api python test_app.py

    - name: Stop containers
      run: docker compose down


