name: Simple CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download code
      uses: actions/checkout@v3

    - name: Start Docker Compose
      run: |
        docker compose up -d --build
        echo "Waiting for services..."
        sleep 20

    - name: Check container status
      run: docker compose ps

    - name: Show API Logs
      run: docker compose logs api

    - name: Show DB Logs
      run: docker compose logs db

    - name: Run tests
      run: docker compose exec -T api python test_app.py

    - name: Stop services
      run: docker compose down



